# Generated by Django 3.0 on 2019-12-03 03:30

import blog.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name='标题')),
                ('sub_title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='子标题')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=blog.models.content_file_name, verbose_name='缩略图')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_by', models.IntegerField(verbose_name='创建人')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_by', models.IntegerField(verbose_name='更新人')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
    ]
